# File lists not yet supported
# Call: python manipulate_land_input.py
input:
  "/data/icon/pool/data/ICON/grids/private/jsbach/mpim/0013/land/r0001/*11pfts*"

output:
  "bc_land_frac_13pfts_1979.nc"

old_variable:
  "fract_pft11"

new_variables:
  [ 'fract_pft12', 'fract_pft13' ]

# fraction of old variable, fraction of new variables
fractions:
  [ 0.7, 0.225, 0.075 ]