# File lists not yet supported
# Change configuration file name in python script
input:
  "/data/icon/LUH_scaled_transitions_T63_2000.nc"
output:
  "hbp_LUH_scaled_transitions_T63_2000.nc"

old_variable:
  "crop2natural"

new_variables:
  [ "crop2hbp" ]

# fraction of old variable, fraction of new variables
fractions:
  [ 0.98, 0.02 ]